print ("WELCOME TO THE FUTURE")
a = input("Enter you name: ")
b= input("Date of year: ")
b= int(b)
c= input("Your Rashi: ")
print("Hi",(a),"You are very Lucky")
print("Your age is",(2021-b))
print ("According to your Rashi Name",[c])
print("At the age of",(2031-b),"YOU WILL BECOME A BILLIONARE")